http: 
  host: ${HTTP_HOST}
  port: ${HTTP_PORT}

postgres:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT_INTERNAL}
  user: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  db: ${DATABASE_NAME}

jwt:
  secret: ${JWT_SECRET}

example:
  message: ${EXAMPLE_MESSAGE}
